In [9]:
import numpy as np
# Setting the random seed, feel free to change it and see different solutions.
np.random.seed(42)

def stepFunction(t):
    if t >= 0:
        return 1
    return 0

def prediction(X, W, b):
    return stepFunction((np.matmul(X,W)+b)[0])

# TODO: Fill in the code below to implement the perceptron trick.
# The function should receive as inputs the data X, the labels y,
# the weights W (as an array), and the bias b,
# update the weights and bias W, b, according to the perceptron algorithm,
# and return W and b.
def perceptronStep(X, y, W, b, learn_rate = 0.01):
    # Fill in code
    for i in range(len(X)):
        y_hat = prediction(X[i],W,b)
        if y[i]-y_hat == 1:
            W[0] += X[i][0]*learn_rate
            W[1] += X[i][1]*learn_rate
            b += learn_rate
        elif y[i]-y_hat == -1:
            W[0] -= X[i][0]*learn_rate
            W[1] -= X[i][1]*learn_rate
            b -= learn_rate
    return W, b
    
    
    
    return W, b
    
# This function runs the perceptron algorithm repeatedly on the dataset,
# and returns a few of the boundary lines obtained in the iterations,
# for plotting purposes.
# Feel free to play with the learning rate and the num_epochs,
# and see your results plotted below.
def trainPerceptronAlgorithm(X, y, learn_rate = 0.01, num_epochs = 25):
    x_min, x_max = min(X.T[0]), max(X.T[0])
    y_min, y_max = min(X.T[1]), max(X.T[1])
    W = np.array(np.random.rand(2,1))
    b = np.random.rand(1)[0] + x_max
    # These are the solution lines that get plotted below.
    boundary_lines = []
    for i in range(num_epochs):
        # In each epoch, we apply the perceptron step.
        W, b = perceptronStep(X, y, W, b, learn_rate)
        boundary_lines.append((-W[0]/W[1], -b/W[1]))
    return boundary_lines

In [2]:
import pandas as pd

In [8]:
df = pd.read_csv('./data.csv')
df.head()

x1        x2  y
0  0.78051 -0.063669  1
1  0.28774  0.291390  1
2  0.40714  0.178780  1
3  0.29230  0.421700  1
4  0.50922  0.352560  1

In [27]:
np.array(df[['x1','x2']])[0]

0.78051

In [17]:
df['y']

0     1
1     1
2     1
3     1
4     1
5     1
6     1
7     1
8     1
9     1
10    1
11    1
12    1
13    1
14    1
15    1
16    1
17    1
18    1
19    1
20    1
21    1
22    1
23    1
24    1
25    1
26    1
27    1
28    1
29    1
     ..
70    0
71    0
72    0
73    0
74    0
75    0
76    0
77    0
78    0
79    0
80    0
81    0
82    0
83    0
84    0
85    0
86    0
87    0
88    0
89    0
90    0
91    0
92    0
93    0
94    0
95    0
96    0
97    0
98    0
99    0
Name: y, Length: 100, dtype: int64

In [18]:
np.array(df['y'])

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [21]:
np.array(df['y'])[0]

1

In [28]:
trainPerceptronAlgorithm(np.array(df[['x1','x2']]),np.array(df['y']))

[(array([3.5679513]), array([4.97079108])),
 (array([0.3425572]), array([0.42998433])),
 (array([0.24930367]), array([0.33090314])),
 (array([0.20269105]), array([0.35539945])),
 (array([0.1693971]), array([0.38177774])),
 (array([0.12333581]), array([0.38388612])),
 (array([0.09695899]), array([0.41300582])),
 (array([0.05955739]), array([0.41742306])),
 (array([0.03447816]), array([0.44843148])),
 (array([0.00483292]), array([0.45383676])),
 (array([-0.02553571]), array([0.45937393])),
 (array([-0.05117847]), array([0.46397324])),
 (array([-0.06851791]), array([0.49903297])),
 (array([-0.09485408]), array([0.50563539])),
 (array([-0.12189648]), array([0.51241485])),
 (array([-0.14967388]), array([0.51937859])),
 (array([-0.17821668]), array([0.5265342])),
 (array([-0.19952008]), array([0.5322499])),
 (array([-0.22129106]), array([0.53809104])),
 (array([-0.23412324]), array([0.57779364])),
 (array([-0.25643702]), array([0.58577517])),
 (array([-0.27937592]), array([0.5939803])),
 (ar

In [23]:
X[i]

NameError: name 'X' is not defined