In [ ]:
"""
file:///Users/huangqiliang/Downloads/%E6%B7%B1%E5%BA%A6%E5%AD%A6%E4%B9%A0%20v3.0.0/Part%2002-Module%2002-Lesson%2001_%E5%AE%9E%E7%8E%B0%E6%A2%AF%E5%BA%A6%E4%B8%8B%E9%99%8D/07.%20%E5%8F%8D%E5%90%91%E4%BC%A0%E6%92%AD.html
"""

In [2]:
X

array([ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986])

In [3]:
weights_input_to_hidden

array([[-0.02341534, -0.0234137 ,  0.15792128],
       [ 0.07674347, -0.04694744,  0.054256  ],
       [-0.04634177, -0.04657298,  0.02419623],
       [-0.19132802, -0.17249178, -0.05622875]])

In [4]:
weights_hidden_to_output

array([[-0.10128311,  0.03142473],
       [-0.09080241, -0.14123037],
       [ 0.14656488, -0.02257763]])

In [12]:
import numpy as np

def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1/(1+np.exp(-x))

# Network size
N_input = 4
N_hidden = 3
N_output = 2

np.random.seed(42)
# Make some fake data
X = np.random.randn(4)

weights_input_to_hidden = np.random.normal(0, scale=0.1, size=(N_input, N_hidden))
weights_hidden_to_output = np.random.normal(0, scale=0.1, size=(N_hidden, N_output))


# TODO: Make a forward pass through the network
hidden_layer_in = np.dot(X, weights_input_to_hidden)
hidden_layer_out = sigmoid(hidden_layer_in)

print('Hidden-layer Output:')
print(hidden_layer_out)

output_layer_in = np.dot(hidden_layer_out, weights_hidden_to_output)
output_layer_out = sigmoid(output_layer_in)

print('Output-layer Output:')
print(output_layer_out)

Hidden-layer Output:
[0.41492192 0.42604313 0.5002434 ]
Output-layer Output:
[0.49815196 0.48539772]


array([-0.34365494, -0.29801368,  0.00097362])