In [1]:
import numpy as np

In [2]:
A = np.matrix([[1,-2],[0,1]])
B = np.matrix([[1,0],[0,-0.5]])

In [3]:
A*B

matrix([[ 1. ,  1. ],
        [ 0. , -0.5]])

In [5]:
B*A

matrix([[ 1. , -2. ],
        [ 0. , -0.5]])

In [6]:
A = np.matrix([[1,3],[0,1]])
B = np.matrix([[4,5],[2,6]])

In [7]:
A*B

matrix([[10, 23],
        [ 2,  6]])

In [8]:
B*A

matrix([[ 4, 17],
        [ 2, 12]])

In [10]:
C = np.matrix([[2,5,4],
               [1,6,8]])

In [11]:
A*B*C

matrix([[ 43, 188, 224],
        [ 10,  46,  56]])

In [12]:
A*(B*C)

matrix([[ 43, 188, 224],
        [ 10,  46,  56]])

In [ ]:
"""
代理产品



"""